// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VerificacaoDeSenha.Data;

#nullable disable

namespace VerificacaoDeSenha.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220701015130_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VerificacaoDeSenha.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("dataVerificado")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("expiraToken")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("reseteSenha")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("senha")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("senhaHash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("verificaToken")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
